site_name: Gluu Docs
site_description: Documenation for the Gluu Server
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2016, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs
theme_dir: theme 
extra:
    version: '2.4.4'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Installation Guide:
    - Single Setup:
        - '1 Preparing VM': 'installation-guide/index.md'
        - '2 Install Gluu Server': 'installation-guide/install.md'
        - '2.5 Setup Script Options': 'installation-guide/setup_py.md'
    - Cluster Setup: 
        - '3 Cluster Deployment Guide': 'cluster/index.md'
    - Upgrade Gluu Server: 
        - '4 Upgrade Guide' : 'upgrade/index.md'

- Administration Interface:
        - '1. Introduction to oxTrust': 'oxtrust/index.md'

- Administration Guide:
        - '1. Introduction' : 'admin-guide/index.md'
        - '2. SAML': 'admin-guide/authentication-protocol-saml.md' 
        - '3 Test SAML': 'admin-guide/authentication-protocol-saml-test.md'
        - '4. OpenID Connect': 'admin-guide/authentication-protocol-openid.md'
        - '5. Test OpenID': 'admin-guide/authentication-protocol-openid-test.md'
        - '6. UMA': 'admin-guide/uma.md'
        - '7. SCIM': 'admin-guide/scim.md'

- Reference Guide:
        - 1. 'Introduction': 'reference-guide/index.md'
