site_name: Gluu Docs
site_description: Documenation for the Gluu Server
#site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs
theme: readthedocs
theme_dir: ./theme/mkdocs/
pages:

- Home: 'index.md'

- Introduction:
    - 'Summary': 'introduction/index.md'
    - 'History': 'introduction/history.md'
    - 'Design Goals': 'introduction/design.md'
    - 'Gluu Server Architecture': 'introduction/architecture.md'

- Installation Guide:
    - Single Setup:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Ubuntu 14.04 (Trusty)': 'installation-guide/ubuntu14.md'
        - 'Ubuntu 16.04 (Xenial)': 'installation-guide/ubuntu16.md'
        - 'CentOS 6.x': 'installation-guide/centos6.md'
        - 'CentOS 7.2': 'installation-guide/centos7.md'
        - 'RHEL 6.x': 'installation-guide/rhel6.md'
        - 'RHEL 7': 'installation-guide/rhel7.md'
        - 'Debian': 'installation-guide/debian.md'

- Upgrade Guide:
    - 'Upgrate Gluu Server': 'upgrade/index.md'
