site_name: Gluu Docs
site_description: Documenation for the Gluu Server
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2016, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs
theme_dir: theme
extra:
    version: '2.4.4'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Installation Guide:
    - Single Setup:
        - '1 Preparing VM': 'installation-guide/index.md'
        - '2 Install Gluu Server': 'installation-guide/install.md'
        - '3 Setup Script Options': 'installation-guide/setup_py.md'
    - Cluster Setup:
        - '4 Cluster Deployment Guide': 'cluster/index.md'
    - Upgrade Gluu Server:
        - '5 Upgrade Guide' : 'upgrade/index.md'
    - Patch Gluu Server:
        - 'Update Gluu CE' : 'update/index.md'
