site_name: Gluu Docs
site_description: Documenation for the Gluu Server
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2016, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs
theme_dir: theme 
extra:
    version: '2.4.4'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
    
- 1.Introduction:
    - '1.1 Summary': 'introduction/index.md'
    - '1.2 History': 'introduction/history.md'
    - '1.3 Design Goals': 'introduction/design.md'
    - '1.4 Gluu Server Architecture': 'introduction/architecture.md'

- Installation Guide:
    - Single Setup:
        - '1 Preparing VM': 'installation-guide/index.md'
        - '2 Install Gluu Server': 'installation-guide/install.md'
        - '2.5 Setup Script Options': 'installation-guide/setup_py.md'
    - Cluster Setup: 
        - '3.1 Csync Install Guide': 'cluster/csync-installation.md'
        - '3.2 Cluster Deployment Guide': 'cluster/index.md'
    - Upgrade Gluu Server: 
        - '4.1 Upgrade Guide' : 'upgrade/index.md'

- Administration Guide:
        - '1. Admin Interface (oxTrust)' : 'admin-guide/index.md'
        - '2. Authentication Protocol': 'admin-guide/authentication-protocol.md' 

- Reference Guide:
        - 1. 'Introduction': 'reference-guide/index.md'
