site_name: Gluu Docs
site_description: Documenation for the Gluu Server
#site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2016, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs
theme: readthedocs
theme_dir: ./theme/mkdocs/
pages:

- Home: 'index.md'
    
- Introduction:
    - 'Summary': 'introduction/index.md'
    - 'History': 'introduction/history.md'
    - 'Design Goals': 'introduction/design.md'
    - 'Gluu Server Architecture': 'introduction/architecture.md'

- Installation Guide:
    - Single Setup:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Ubuntu': 'installation-guide/ubuntu.md'
        - 'CentOS': 'installation-guide/centos.md'
        - 'RHEL': 'installation-guide/rhel.md'
        - 'Debian': 'installation-guide/debian.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
        - 'Microsoft Azure Guide': 'installation-guide/azure.md'
    - Cluster Setup: 
        - 'Cluster Deployment Guide': 'cluster/index.md'
        - 'Csync Install Guide': 'cluster/csync-installation.md'
    - Upgrade Gluu Server: 
        - 'Upgrade Guide' : 'upgrade/index.md'

- Administration Guide:
   - 'Admin GUI (oxTrust)' : 'adminn-guide/index.md' 
