site_name: Gluu Docs
site_description: Documenation for the Gluu Server
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2016, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs
theme_dir: theme
extra:
    version: '3.0.0'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Installation Guide:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Install Gluu Server': 'installation-guide/install.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
        - 'Cluster with CE': 'installation-guide/cluster.md'
- Upgrade/Patch Guide:
        - 'Upgrade Gluu Server' : 'upgrade/index.md'
        - 'Patch Gluu Server' : 'upgrade/patch.md'

- Administration Guide:
        - 'oxTrust Admin Interface' : ' admin-guide/index.md'
	- 'Authentication Protocols' : 'admin-guide/auth-protocol.md'
	- 'Authntication Managment' : 'admin-guide/auth-management.md'
	- 'Multi Factor Authentication' : 'admin-guide/multi-factor-auth.md'
	- 'Manage & Configure Users' : 'admin-guide/user-group.md'
	- 'Configure Log' : 'admin-guide/logs.md'
	- 'Gluu for Mobile' : 'admin-guide/mobile.md'
	- 'Self-Services for Users' : 'admin-guide/self-service.md'
	- 'Configure OpenID Clients' : 'admin-guide/clients.md'
	- 'Configure SAML SSO' : 'admin-guide/saml.md'

